import os
import sys
import numpy as np
import psi4
import resp

def verify_bf4_psi4():
    print("Starting PSI4/RESP calculation for BF4...")
    
    # 1. Structure (Angstrom)
    # Using the coordinates from your PDB for BF4
    mol_str = """
    -1 1
    B    0.948   0.055  -0.065
    F    0.470  -1.289   0.059
    F    0.470   0.835   1.037
    F    0.470   0.619  -1.291
    F    2.379   0.055  -0.065
    """
    psi_mol = psi4.geometry(mol_str)
    
    # 2. PSI4 Calculation
    psi4.set_options({
        'basis': '6-31G*',
        'scf_type': 'df',
        'guess': 'sad'
    })
    
    print("Running energy calculation...")
    e, wfn = psi4.energy('b3lyp', return_wfn=True)
    
    # 3. RESP Fitting
    # We define symmetry: atoms 2,3,4,5 are F atoms
    # In psi4/resp, symmetry is often handled via atom grouping
    # The resp package fit_charges expects (coords, esp, grid, charge)
    # but it also has a high-level API if we have the wfn
    
    # Generate Grid using PSI4's internal tools or simple shell
    # Actually, the 'resp' package has a plugin for PSI4
    
    from resp import RESPOptions, fit_charges
    
    # For now, let's use the ESP points generated by PSI4
    # This is the most accurate way
    print("Calculating ESP grid...")
    # Generate points around the molecule
    # Standard RESP grid parameters
    # Note: This part varies by version, we use a common approach
    
    # Using the resp library's fit_charges directly
    # For stability, we use its built-in hyperbolic restraint
    options = RESPOptions(restraint_height=0.0005, restraint_width=0.1)
    
    # To get ESP from PSI4 WFN:
    # We need to evaluate the potential at some grid points
    # Let's generate a simple grid here
    atoms = np.array([psi_mol.xyz(i) for i in range(psi_mol.natom())]) # Bohr
    symbols = [psi_mol.symbol(i) for i in range(psi_mol.natom())]
    
    grid_pts = []
    vdw_radii = {'B': 1.9, 'F': 1.47} # Bohr
    for i in range(psi_mol.natm()):
        r_vdw = vdw_radii.get(symbols[i], 1.5) * 1.89 # Convert to Bohr
        for factor in [1.4, 1.6, 1.8, 2.0]:
            pts = np.random.normal(0, 1, (500, 3))
            pts /= np.linalg.norm(pts, axis=1)[:, None]
            grid_pts.append(atoms[i] + pts * r_vdw * factor)
    grid_pts = np.vstack(grid_pts)
    
    print(f"Number of grid points: {len(grid_pts)}")
    
    # Calculate ESP at these points using PSI4
    # V = V_nuc + V_elec
    esp_eval = psi4.core.ESPPropCalc(wfn)
    phi_pts = psi4.core.Vector.from_array(grid_pts)
    # PSI4 potential evaluation
    v_total = esp_eval.compute_esp_at_points(phi_pts).to_array()
    
    print("Fitting charges...")
    charges = fit_charges(atoms, v_total, grid_pts, -1.0, options)
    
    print("\n--- BF4 PSI4/RESP Final Results ---")
    for i, s in enumerate(symbols):
        print(f"Atom {i+1} {s}: {charges[i]:.4f}")
    print(f"Total: {np.sum(charges):.4f}")

if __name__ == "__main__":
    verify_bf4_psi4()
